## 4.1 画像データ

### 4.1.2 画像データのロード

In [1]:
import imageio

img_arr = imageio.imread('Books/PyTorch_intro/data/bobby.jpg')
img_arr.shape

/var/folders/bn/wxtwk7w55bd3xbywj40g_mfw0000gp/T/ipykernel_5052/3814436136.py:3: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  img_arr = imageio.imread('Books/PyTorch_intro/data/bobby.jpg')


(720, 1280, 3)

In [2]:
print(type(img_arr))

<class 'numpy.ndarray'>


img_arrは(height, width, channel)のNumpyオブジェクト。  

PyTorchのモジュールでは(Channel, height, width)でデータを配置する必要がある

In [3]:
import torch

In [6]:
img = torch.from_numpy(img_arr)
print(type(img))
out = img.permute(2, 0, 1)
out.shape

<class 'torch.Tensor'>


torch.Size([3, 720, 1280])

NNに入力する複数枚の画像データセットを作成し, 画像テンソルの1次元目にバッチ次元を用意して  
(N, C, H, W)という形にして画像セットを表せる.

In [7]:
batch_size = 3
batch = torch.zeros(batch_size, 3, 256, 256, dtype=torch.uint8)

In [9]:
import os

data_dir = 'Books/PyTorch_intro/Chapter4/data/image-cats/'
filenames = [name for name in os.listdir(data_dir)
             if os.path.splitext(name)[-1] == '.png']
print(filenames)

['cat1.png', 'cat2.png', 'cat3.png']


In [13]:
for i, filename in enumerate(filenames):
    img_arr = imageio.imread(os.path.join(data_dir, filename))
    img_t = torch.from_numpy(img_arr)
    img_t = img_t.permute(2, 0, 1)
    img_t = img_t[:3] # 画像によっては3次元目にアルファ値が存在する
    batch[i] = img_t
print(batch.shape)

torch.Size([3, 3, 256, 256])


/var/folders/bn/wxtwk7w55bd3xbywj40g_mfw0000gp/T/ipykernel_5052/3624832837.py:2: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  img_arr = imageio.imread(os.path.join(data_dir, filename))


### 4.1.4 データの正規化

NNは0-1, または-1から1の範囲にデータがあることが好ましい.

In [15]:
batch = batch.float()
batch /= 255.0
print(batch)

tensor([[[[2.3991e-03, 2.3376e-03, 1.9070e-03,  ..., 2.3068e-03,
           2.2914e-03, 2.4298e-03],
          [2.6759e-03, 2.0607e-03, 2.5375e-03,  ..., 1.8454e-03,
           2.0915e-03, 2.1223e-03],
          [1.9531e-03, 2.3991e-03, 1.6455e-03,  ..., 2.0146e-03,
           2.1992e-03, 2.5221e-03],
          ...,
          [1.7839e-03, 1.9992e-03, 1.9839e-03,  ..., 1.9531e-03,
           1.8147e-03, 1.7224e-03],
          [1.9839e-03, 1.9992e-03, 1.8916e-03,  ..., 1.7686e-03,
           1.8608e-03, 1.7532e-03],
          [1.9839e-03, 1.8916e-03, 1.8147e-03,  ..., 1.7378e-03,
           1.8608e-03, 1.8454e-03]],

         [[2.1376e-03, 2.0761e-03, 1.6763e-03,  ..., 2.0761e-03,
           2.0761e-03, 2.2607e-03],
          [2.4606e-03, 1.8301e-03, 2.2914e-03,  ..., 1.6148e-03,
           1.8762e-03, 1.9070e-03],
          [1.7378e-03, 2.1530e-03, 1.3841e-03,  ..., 1.8147e-03,
           1.9839e-03, 2.3376e-03],
          ...,
          [1.5225e-03, 1.6917e-03, 1.7070e-03,  ..., 1.7993

### 4.2.1 特殊フォーマットの読み込み

In [26]:
import imageio
# 全角のファイル名だった
dir_path = 'Books/PyTorch_intro/Chapter4/data/volumetric-dicom/2-LUNG 3.0  B70f-04083'
vol_arr = imageio.volread(dir_path, 'DICOM')
vol_arr.shape

Reading DICOM (examining files): 1/99 files (1.0%99/99 files (100.0%)
  Found 1 correct series.
Reading DICOM (loading data): 99/99  (100.0%)


(99, 512, 512)

次元数がないためunsqueezeで次元追加

In [28]:
vol = torch.from_numpy(vol_arr).float()
# 0次元目に追加
vol = torch.unsqueeze(vol, 0)
vol.shape

torch.Size([1, 99, 512, 512])

### 4.3.2 wineデータをテンソルとして読み込む

In [29]:
import csv
import numpy as np
wine_path = 'Books/PyTorch_intro/Chapter4/data/tabular-wine/winequality-white.csv'
wineq_numpy = np.loadtxt(wine_path, dtype=np.float32, delimiter=";", skiprows=1)
wineq_numpy

array([[ 7.  ,  0.27,  0.36, ...,  0.45,  8.8 ,  6.  ],
       [ 6.3 ,  0.3 ,  0.34, ...,  0.49,  9.5 ,  6.  ],
       [ 8.1 ,  0.28,  0.4 , ...,  0.44, 10.1 ,  6.  ],
       ...,
       [ 6.5 ,  0.24,  0.19, ...,  0.46,  9.4 ,  6.  ],
       [ 5.5 ,  0.29,  0.3 , ...,  0.38, 12.8 ,  7.  ],
       [ 6.  ,  0.21,  0.38, ...,  0.32, 11.8 ,  6.  ]], dtype=float32)

In [30]:
col_list = next(csv.reader(open(wine_path), delimiter=';'))
wineq_numpy.shape, col_list

((4898, 12),
 ['fixed acidity',
  'volatile acidity',
  'citric acid',
  'residual sugar',
  'chlorides',
  'free sulfur dioxide',
  'total sulfur dioxide',
  'density',
  'pH',
  'sulphates',
  'alcohol',
  'quality'])

次にNumpy配列をテンソルに変換

In [31]:
wineq = torch.from_numpy(wineq_numpy)
wineq.shape, wineq.dtype

(torch.Size([4898, 12]), torch.float32)

### 4.3.3 スコアの表現

In [33]:
data = wineq[:, :-1] # 最後の列以外を選択
data, data.shape

(tensor([[ 7.0000,  0.2700,  0.3600,  ...,  3.0000,  0.4500,  8.8000],
         [ 6.3000,  0.3000,  0.3400,  ...,  3.3000,  0.4900,  9.5000],
         [ 8.1000,  0.2800,  0.4000,  ...,  3.2600,  0.4400, 10.1000],
         ...,
         [ 6.5000,  0.2400,  0.1900,  ...,  2.9900,  0.4600,  9.4000],
         [ 5.5000,  0.2900,  0.3000,  ...,  3.3400,  0.3800, 12.8000],
         [ 6.0000,  0.2100,  0.3800,  ...,  3.2600,  0.3200, 11.8000]]),
 torch.Size([4898, 11]))

In [34]:
target = wineq[:, -1]
target, target.shape

(tensor([6., 6., 6.,  ..., 6., 7., 6.]), torch.Size([4898]))

求めたい目的変数をラベルのテンソルに変換するには, 単純にスコアを整数値として扱う方法がある.

In [38]:
target = wineq[:, -1].long()

target, target.shape

(tensor([6, 6, 6,  ..., 6, 7, 6]), torch.Size([4898]))

### 4.3.4 one-hot encoding

10のスコアそれぞれを10要素のベクトルにエンコードする. しかしスコアの場合は単純に整数値にエンコードした方が順序尺度での扱いができていい.

In [40]:
target_onehot = torch.zeros(target.shape[0], 10)
target_onehot.scatter_(1, target.unsqueeze(1), 1.0)
target_onehot.shape

torch.Size([4898, 10])

scatter_の動作を確認する.  
- ワンホットにする次元
- ワンホットで分布させる列インデックスの形を示したテンソル
- 値として与える要素を示すスカラテンソル

In [41]:
target_unsqueezed = target.unsqueeze(1)
target_unsqueezed

tensor([[6],
        [6],
        [6],
        ...,
        [6],
        [7],
        [6]])

### 4.3.5 カテゴリカルラベルをする場合

In [43]:
data, data.shape

(tensor([[ 7.0000,  0.2700,  0.3600,  ...,  3.0000,  0.4500,  8.8000],
         [ 6.3000,  0.3000,  0.3400,  ...,  3.3000,  0.4900,  9.5000],
         [ 8.1000,  0.2800,  0.4000,  ...,  3.2600,  0.4400, 10.1000],
         ...,
         [ 6.5000,  0.2400,  0.1900,  ...,  2.9900,  0.4600,  9.4000],
         [ 5.5000,  0.2900,  0.3000,  ...,  3.3400,  0.3800, 12.8000],
         [ 6.0000,  0.2100,  0.3800,  ...,  3.2600,  0.3200, 11.8000]]),
 torch.Size([4898, 11]))

In [46]:
data_mean = torch.mean(data, dim=0) # dim=0は次元0に沿って計算
data_mean

tensor([6.8548e+00, 2.7824e-01, 3.3419e-01, 6.3914e+00, 4.5772e-02, 3.5308e+01,
        1.3836e+02, 9.9403e-01, 3.1883e+00, 4.8985e-01, 1.0514e+01])

In [47]:
data_var = torch.var(data, dim=0)
data_var

tensor([7.1211e-01, 1.0160e-02, 1.4646e-02, 2.5726e+01, 4.7733e-04, 2.8924e+02,
        1.8061e+03, 8.9455e-06, 2.2801e-02, 1.3025e-02, 1.5144e+00])

In [49]:
data_normalized = (data - data_mean) / torch.sqrt(data_var)
data_normalized, data_normalized.shape

(tensor([[ 1.7208e-01, -8.1761e-02,  2.1326e-01,  ..., -1.2468e+00,
          -3.4915e-01, -1.3930e+00],
         [-6.5743e-01,  2.1587e-01,  4.7996e-02,  ...,  7.3995e-01,
           1.3422e-03, -8.2419e-01],
         [ 1.4756e+00,  1.7450e-02,  5.4378e-01,  ...,  4.7505e-01,
          -4.3677e-01, -3.3663e-01],
         ...,
         [-4.2043e-01, -3.7940e-01, -1.1915e+00,  ..., -1.3130e+00,
          -2.6153e-01, -9.0545e-01],
         [-1.6054e+00,  1.1666e-01, -2.8253e-01,  ...,  1.0049e+00,
          -9.6251e-01,  1.8574e+00],
         [-1.0129e+00, -6.7703e-01,  3.7852e-01,  ...,  4.7505e-01,
          -1.4882e+00,  1.0448e+00]]),
 torch.Size([4898, 11]))

### 4.3.6 閾値の特定

ターゲットのどの行が3以下の品質スコアになっているのか求める

In [51]:
bad_indexes = target <= 3
bad_indexes.shape, bad_indexes.dtype, bad_indexes.sum()

(torch.Size([4898]), torch.bool, tensor(20))

bad_indexesの要素のうち, 20個がTrueになった.

In [53]:
bad_data = data[bad_indexes]
bad_data.shape

torch.Size([20, 11])

In [56]:
bad_data = data[target <= 3]
mid_data = data[(target > 3) & (target < 7)]
good_data = data[target >= 7]

In [57]:
bad_mean = torch.mean(bad_data, dim=0)
mid_mean = torch.mean(mid_data, dim=0)
good_mean = torch.mean(good_data, dim=0)

In [58]:
for i, args in enumerate(zip(col_list, bad_mean, mid_mean, good_mean)):
    print('{:2} {:20} {:6.2f} {:6.2f} {:6.2f}'.format(i, *args))

 0 fixed acidity          7.60   6.89   6.73
 1 volatile acidity       0.33   0.28   0.27
 2 citric acid            0.34   0.34   0.33
 3 residual sugar         6.39   6.71   5.26
 4 chlorides              0.05   0.05   0.04
 5 free sulfur dioxide   53.33  35.42  34.55
 6 total sulfur dioxide 170.60 141.83 125.25
 7 density                0.99   0.99   0.99
 8 pH                     3.19   3.18   3.22
 9 sulphates              0.47   0.49   0.50
10 alcohol               10.34  10.26  11.42


bad_dataに二酸化硫黄の総量が多いように見える.  
閾値を使って平均値以下のindexを求める.

In [60]:
total_sulfur_threshold = 141.83
total_sulfur_data = data[:, 6]
predicted_indexes = torch.lt(total_sulfur_data, total_sulfur_threshold)
predicted_indexes.shape, predicted_indexes.dtype, predicted_indexes.sum()

(torch.Size([4898]), torch.bool, tensor(2727))

## 4.4 時系列データ

### 4.4.1 時間軸の追加