<a href="https://colab.research.google.com/github/morixxfoxdata/TIL/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch入門：1. テンソル

テンソルは配列や行列によく似ている.

PyTorchではテンソル型の変数を利用する.

テンソルはnumpyのndarraysに似ているが, GPUで動作できるという違いがある.

テンソルとNumPy配列は同じメモリを共有できるため, 2つの型の間での変換時にはデータをコピーする必要がない.

In [3]:
%matplotlib inline

In [4]:
import torch
import numpy as np

# テンソルの初期化

**データから直接テンソルに変換**

直接変換した際は, データ型が自動で推測される.

In [5]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

In [6]:
print(type(data))
print(type(x_data))

<class 'list'>
<class 'torch.Tensor'>


**NumPy arrayからテンソルに変換**

tensorとNumpy arraysは相互に互換可能

In [7]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [8]:
print(type(np_array))
print(type(x_np))

<class 'numpy.ndarray'>
<class 'torch.Tensor'>


**他のテンソルからの作成**

他のTensorから新しいTensorを作成する場合, 明示的に上書きされない限り,  
引数のTensorのプロパティ（形状,　データ型）を保持する

In [9]:
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.1998, 0.1610],
        [0.7962, 0.8107]]) 



**ランダム値や定数のテンソルの作成**

shapeは, テンソルの次元を示すタプル.

以下の例では, shapeからテンソルのサイズを決めている

In [10]:
shape = (2, 3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.5978, 0.4732, 0.3031],
        [0.9214, 0.9862, 0.0968]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


# テンソルの属性変数

テンソルは属性変数として、形状、データ型、保存されているデバイスを保持している

In [11]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


# テンソルの操作

PyTorchでは、算術、線形代数、行列操作など、100種類以上のテンソル演算ができる

各操作はGPUで実行可能。

デフォルトではテンソルはCPU上で作られる。

以下のようにしてGPUへ移動できるが、大きなテンソルをコピーすると時間とメモリ面でコストがかかる。

In [13]:
torch.backends.mps.is_available()

True

In [14]:
if torch.backends.mps.is_available():
    tensor = tensor.to('mps')

**numpy-likeなindexingとslicing:**

In [15]:
tensor = torch.ones(4, 4)
print('First row:', tensor[0])
print('First column:', tensor[:, 0])
print('Last column:', tensor[:, -1])
tensor[:, 1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


**tensorの結合**

torch.catを用いて特定の次元に沿って結合できる

In [16]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)
print(t1.shape)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])
torch.Size([4, 12])


torch.stackについても試す

In [17]:
t2 = torch.stack((tensor, tensor), dim=2)
print(t2)
print(t2.shape)

tensor([[[1., 1.],
         [0., 0.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [0., 0.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [0., 0.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [0., 0.],
         [1., 1.],
         [1., 1.]]])
torch.Size([4, 4, 2])


catは既存の次元に沿って結合だが,  
stackは次元を増やすことができる

**算術演算**

In [18]:
# 2つのテンソル行列の掛け算
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
print(tensor)
y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)
print(y3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


In [19]:
# 要素ごとの積
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

**1要素のテンソル**

１要素のテンソルを扱うには, .item()を使用することでPythonの数値型に変更できる

In [20]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


**インプレース操作**

演算結果をオペランドに格納する演算をインプレースという.

In [21]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


メモリ節約になるが演算履歴が失われるので微分計算の際に問題になることに注意

# NumPyとの交換

CPU上のテンソルとNumpy arraysは同じメモリを共有でき、相互変換が容易

**Tensor to NumPy array**

In [22]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


この際、テンソルが変化するとNumpy側も変化する（tとnがメモリを共有しているため）

In [23]:
t.add_(1)
print(f"n:{n}")

n:[2. 2. 2. 2. 2.]


**Numpy arrays to Tensor**

In [24]:
n = np.ones(5)
t = torch.from_numpy(n)

Numpy側の変化はテンソル側にも反映される

In [25]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
