## numpy 100 Exercises

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
print(np.__version__)
print(np.show_config())

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/anaconda3/include
    lib directory: /opt/anaconda3/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK=0 NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP=0 CORE2 MAX_THREADS=128
    pc file directory: /opt/anaconda3/lib/pkgconfig
    version: 0.3.21
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep4499572816
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -march=core2, -mtune=haswell, -mssse3, -ftree-vectorize, -fPIC, -fPIE, -fstack-protector-strong,
      -O2, -pipe, -isystem, /opt/anaconda3/include, -fdebug-prefix-map=/var/folders/c_/qfmhj66j0tn016nkx_th4hxm0000gp/T/abs_b7iptlxgej/croot/numpy_and_numpy_base_1708638622773/work=/usr/local/src/conda/numpy-base-1.26.4,
      -fdeb

#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
vec_3 = np.zeros(10)
# vec_3 = np.zeros((10))
print(vec_3.shape)

(10,)


#### 4. How to find the memory size of any array (★☆☆)

In [5]:
arr_4 = np.array([1, 2, 3])
print(arr_4.nbytes, 'bytes')
print(vec_3.nbytes, 'bytes')

24 bytes
80 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [6]:
print(help(np.add))

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [7]:
vec_6 = np.zeros(10)
vec_6[4] = 1
print(vec_6)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [8]:
# vec_7 = np.array([i for i in range(10, 49)])
vec_7 = np.arange(10, 49)
print(vec_7)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [9]:
vec_8 = np.arange(10, 30)
re_vec_8 = vec_8[::-1]
print(re_vec_8)

[29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [10]:
mat_9 = np.arange(0, 9).reshape((3, 3))
print(mat_9)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [11]:
vec_10 = np.array([1,2,0,0,4,0])
print(np.nonzero(vec_10))
# print(np.where(vec_10!=0))

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [12]:
mat_11 = np.eye(3)
print(mat_11)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [13]:
mat_12 = np.random.rand(3, 3, 3)
print(mat_12)

[[[0.62730987 0.58589338 0.24562094]
  [0.58305229 0.72672301 0.30422755]
  [0.21772278 0.24938848 0.37865658]]

 [[0.18528434 0.20568321 0.81011085]
  [0.36949224 0.8230983  0.51125272]
  [0.60643682 0.81712545 0.36065604]]

 [[0.33663621 0.73254758 0.23736064]
  [0.92639106 0.99145564 0.84572029]
  [0.33176294 0.23641148 0.93916086]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [14]:
mat_13 = np.random.rand(10, 10)
min_value = mat_13.min()
max_value = mat_13.max()
print(min_value, max_value)

0.0004467800189237314 0.9741363399164081


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [15]:
vec_14 = np.random.rand(30)
mean_vec_14 = vec_14.mean()
print(mean_vec_14)

0.4524092644704442


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [16]:
mat_15 = np.ones((5, 5))
# print(mat_15)
mat_15[1:-1, 1:-1] = 0
print(mat_15)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [17]:
mat_16_before = np.ones((3, 3))
print(mat_16_before)
mat_16_after = np.pad(mat_16_before, 1)
print(mat_16_after)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)

In [18]:
print(np.nan == np.nan)
print(0 * np.nan)
# np.nan == np.nan
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

False
nan
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [21]:
mat_18 = np.diag(np.arange(0, 4) + 1, k=-1)
print(mat_18)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]
