## numpy 100 Exercises

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(np.__version__)
print(np.show_config())

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/anaconda3/include
    lib directory: /opt/anaconda3/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK=0 NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP=0 CORE2 MAX_THREADS=128
    pc file directory: /opt/anaconda3/lib/pkgconfig
    version: 0.3.21
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep4499572816
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -march=core2, -mtune=haswell, -mssse3, -ftree-vectorize, -fPIC, -fPIE, -fstack-protector-strong,
      -O2, -pipe, -isystem, /opt/anaconda3/include, -fdebug-prefix-map=/var/folders/c_/qfmhj66j0tn016nkx_th4hxm0000gp/T/abs_b7iptlxgej/croot/numpy_and_numpy_base_1708638622773/work=/usr/local/src/conda/numpy-base-1.26.4,
      -fdeb

#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
vec_3 = np.zeros(10)
# vec_3 = np.zeros((10))
print(vec_3.shape)

(10,)


#### 4. How to find the memory size of any array (★☆☆)

In [4]:
arr_4 = np.array([1, 2, 3])
print(arr_4.nbytes, 'bytes')
print(vec_3.nbytes, 'bytes')

24 bytes
80 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [5]:
print(help(np.add))

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [6]:
vec_6 = np.zeros(10)
vec_6[4] = 1
print(vec_6)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [7]:
# vec_7 = np.array([i for i in range(10, 49)])
vec_7 = np.arange(10, 49)
print(vec_7)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [8]:
vec_8 = np.arange(10, 30)
re_vec_8 = vec_8[::-1]
print(re_vec_8)

[29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [9]:
mat_9 = np.arange(0, 9).reshape((3, 3))
print(mat_9)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [10]:
vec_10 = np.array([1,2,0,0,4,0])
print(np.nonzero(vec_10))
# print(np.where(vec_10!=0))

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [11]:
mat_11 = np.eye(3)
print(mat_11)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [12]:
mat_12 = np.random.rand(3, 3, 3)
print(mat_12)

[[[0.1956199  0.80742022 0.3981434 ]
  [0.93485465 0.02299686 0.12151231]
  [0.25365388 0.01601993 0.1770439 ]]

 [[0.66716261 0.75629256 0.87270334]
  [0.00567826 0.82530839 0.31306941]
  [0.94316015 0.20190755 0.32471618]]

 [[0.54085134 0.46391087 0.18981216]
  [0.72716014 0.46901321 0.87963251]
  [0.01624614 0.65011762 0.9040769 ]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [13]:
mat_13 = np.random.rand(10, 10)
min_value = mat_13.min()
max_value = mat_13.max()
print(min_value, max_value)

0.023436757773238837 0.9809130347486733


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [14]:
vec_14 = np.random.rand(30)
mean_vec_14 = vec_14.mean()
print(mean_vec_14)

0.5252698742504995


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [15]:
mat_15 = np.ones((5, 5))
# print(mat_15)
mat_15[1:-1, 1:-1] = 0
print(mat_15)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [16]:
mat_16_before = np.ones((3, 3))
print(mat_16_before)
mat_16_after = np.pad(mat_16_before, 1)
print(mat_16_after)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)

In [17]:
print(np.nan == np.nan)
print(0 * np.nan)
# np.nan == np.nan
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

False
nan
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [18]:
mat_18 = np.diag(np.arange(0, 4) + 1, k=-1)
print(mat_18)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [19]:
mat_19 = np.zeros((8, 8))
mat_19[1::2, ::2] = 1
mat_19[::2, 1::2] = 1
print(mat_19)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [20]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [23]:
arr_21 = [[0, 1], [1, 0]]
mat_21 = np.tile(arr_21, (4, 4))
print(mat_21)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [26]:
mat_22 = np.random.rand(5,5)
mat_22_norm = (mat_22 - mat_22.mean()) / mat_22.std()
print(mat_22)

[[0.51285872 0.61146979 0.53033095 0.71365851 0.66650366]
 [0.0054974  0.60201445 0.4876141  0.79602407 0.94965106]
 [0.3038655  0.26633449 0.73426685 0.95789763 0.21478036]
 [0.76188873 0.11290688 0.95571812 0.42498437 0.81939559]
 [0.13188612 0.09011855 0.61560515 0.71256598 0.22971744]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [27]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [28]:
mat_24_1 = np.random.rand(5, 3)
mat_24_2 = np.random.rand(3, 2)
print(np.matmul(mat_24_1, mat_24_2))

[[0.20175709 0.89864866]
 [0.31951309 1.07912355]
 [0.23000316 0.81562246]
 [0.21799885 0.63817716]
 [0.15205587 0.58569864]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [41]:
Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)

In [42]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

In [43]:
# Z**Z
# 2 << Z >> 2
# Z <- Z
# 1j*Z
# Z/1/1
# Z<Z>Z

#### 28. What are the result of the following expressions? (★☆☆)

In [44]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/var/folders/bn/wxtwk7w55bd3xbywj40g_mfw0000gp/T/ipykernel_2847/3912170336.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
/var/folders/bn/wxtwk7w55bd3xbywj40g_mfw0000gp/T/ipykernel_2847/3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
/var/folders/bn/wxtwk7w55bd3xbywj40g_mfw0000gp/T/ipykernel_2847/3912170336.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

In [47]:
arr_29 = np.random.uniform(-10, 10, 10)
# print(arr_29)
print(np.copysign(np.ceil(np.abs(arr_29)), arr_29))

# More readable but less efficient
print(np.where(arr_29>0, np.ceil(arr_29), np.floor(arr_29)))

[  4.   2.  -6. -10.  -4.  10. -10.  -6.   9.   7.]
[  4.   2.  -6. -10.  -4.  10. -10.  -6.   9.   7.]


#### 30. How to find common values between two arrays? (★☆☆)

In [48]:
arr_30_1 = np.random.randint(0, 10, 10)
arr_30_2 = np.random.randint(0, 10, 10)
print(np.intersect1d(arr_30_1, arr_30_2))

[1 2 3 4 6]
